[[color]]
hex = "FF0000"
name = "Red"

[[color]]
hex = "FFA500"
name = "Orange"

[[color]]
hex = "FFFF00"
name = "Yellow"

[[color]]
hex = "008000"
name = "Green"

[[color]]
hex = "0000FF"
name = "Blue"

[[color]]
hex = "EE82EE"
name = "Violet"

[[color]]
hex = "A52A2A"
name = "Brown"

[[color]]
hex = "000000"
name = "Black"

[[color]]
hex = "808080"
name = "Grey"

[[color]]
hex = "FFFFFF"
name = "White"

