language: go

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on

install:
  - go install ./...

before_script:
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
